// Code generated by ent, DO NOT EDIT.

package webhook

import (
	"time"
)

const (
	// Label holds the string label denoting the webhook type in the database.
	Label = "webhook"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAppName holds the string denoting the app_name field in the database.
	FieldAppName = "app_name"
	// FieldWebhookURL holds the string denoting the webhook_url field in the database.
	FieldWebhookURL = "webhook_url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the webhook in the database.
	Table = "webhooks"
)

// Columns holds all SQL columns for webhook fields.
var Columns = []string{
	FieldID,
	FieldAppName,
	FieldWebhookURL,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt time.Time
)
